name: CD Deploy to GABIA

on:
  push:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set DB_PW from Secrets
        shell: powershell
        run: |
          "DB_PW=${{ secrets.DB_PW }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build WAR
        working-directory: ./spring
        run: .\gradlew.bat clean bootWar  # Windows에서는 .bat 파일 실행

      - name: Rename WAR to ROOT.war
        shell: powershell
        working-directory: ./spring
        run: |
          Remove-Item ..\deploy -Recurse -Force -ErrorAction SilentlyContinue
          New-Item ..\deploy -ItemType Directory
          Copy-Item .\build\libs\*.war ..\deploy\ROOT.war

      - name: Save SSH private key
        shell: powershell
        run: |
          $key = @"${{ secrets.GABIA_SSH_PRIVATE_KEY }}"@
          $key | Out-File -FilePath "$env:USERPROFILE\.ssh\id_rsa" -Encoding ascii
          icacls "$env:USERPROFILE\.ssh\id_rsa" /inheritance:r /grant:r "$($env:USERNAME):(R)" /c

      - name: Upload WAR to GABIA server (scp)
        shell: powershell
        run: |
          scp -i "$env:USERPROFILE\.ssh\id_rsa" deploy/ROOT.war ${{ secrets.GABIA_USER }}@${{ secrets.GABIA_HOST }}:/usr/local/tomcat9_BE/webapps/pps/

      - name: Restart Tomcat
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GABIA_HOST }}
          username: ${{ secrets.GABIA_USER }}
          key: ${{ secrets.GABIA_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            bash /usr/local/tomcat9_BE/bin/shutdown.sh || true
            sleep 3
            bash /usr/local/tomcat9_BE/bin/startup.sh
